services:
  auth-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5001:5432"
    networks:
      - internal
    volumes:
      - C:\Users\Abdellah Bounab\db_volumes\auth-service-db:/var/lib/postgresql/data


  patient-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5000"
    networks:
      - internal
    volumes:
      - C:\Users\Abdellah Bounab\db_volumes\patient-service-db:/var/lib/postgresql/data

  patient-service:
    image: patient-service:latest
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/patientdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - internal

  auth-service:
    image: auth-service:latest
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      - JWT_SECRET=g1brIEgHUckFn02lhSOxQ6wQWvEc9hLn6mmQFb5D7pRAQnj5xrhyyxtKvyjxiDyLbsHirmcPRtEjiZRxYkLpSmt0Sa0GYVML/MPbgRRQ3pE=
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    networks:
      - internal

  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "4004:4004"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AUTH_SERVICE_URL=http://auth-service:4005
    depends_on:
      - patient-service
      - billing-service
    networks:
      - internal

  billing-service:
    image: billing-service:latest
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal

  analytics-service:
    image: analytics-service:latest
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal

networks:
  internal: